# Generated by Django 2.0.8 on 2018-10-11 01:54
"""
0002_update_field_choices.py
============================
Migration
"""

import boogie.fields.enum_field
import django.db.models.deletion
import ej_conversations.models.vote
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ej_clusters", "0001_first_migration")]

    operations = [
        migrations.AlterField(
            model_name="stereotypevote",
            name="choice",
            field=boogie.fields.enum_field.EnumField(
                ej_conversations.models.vote.Choice, verbose_name="Choice"
            ),
        ),
        migrations.AlterField(
            model_name="stereotypevote",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stereotype_votes",
                to="ej_conversations.Comment",
                verbose_name="Comment",
            ),
        ),
    ]
